### PR TITLE
Renaming env files to reflect their new names in docker.

### PR DESCRIPTION
**Pull request by leonk**
### Context

> Does this issue have a Trello card?

No it's a small change, cherry-picked from a previous PR: https://github.com/ministryofjustice/prisoner-content-hub/pull/755

### Intent

This renames the env files so that they're the same as the environment names in docker, keeping it so everything uses the same name.

### Considerations

For local environments you will need to manually rename the `env` files.  I'm not sure if anything needs to be done in dev/staging/prod?

### Checklist

- [ ] This PR contains **only** changes related to the above card
- [ ] Tests have been added/updated to cover the change
- [ ] Documentation has been updated where appropriate
- [ ] Tested in Development

### CODE REVIEW

**Comment by spikeheap** [comment]
Hey @leonk I've just noticed this PR was left to go a bit stale, sorry! 

I wonder whether we could go the other way, and revert the renaming of the services in `docker-compose.yml`. Prefixing everything with `prisoner-content-hub` feels a bit redundant and makes local dev commands longer. I'd also tried to keep away from the term `backend`, because `drupal` is more meaningful. There's probably an even better name somewhere!

I've got a whole load of 🤷 about which approach is "better", and agree that consistency is good, so we should either merge this :+1:, or revert the changes from https://github.com/ministryofjustice/prisoner-content-hub/pull/754/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3 and https://github.com/ministryofjustice/prisoner-content-hub/pull/754/files#diff-2286cdeca85adb587a9640aa34352ba7c2fb6e49c0129dab05892ff67d0d4c58. 

@andrewrlee do you have a preference?

**Comment by leonk** [comment]
Trying to remember the reason why all the names were changed previously.  I think there was a bit of a mix-and-match approach before, and possibly `prisoner-hub-` cannot be renamed in some places, so it became the standard for everything.

I don't mind renaming `backend` to `drupal` (or possibly `cms`, but fine with `drupal` also).  But I do think it needs to be prefixed, so we're not just referring to `drupal` directly (as I think this could get confused with somekind of internal drupal thing).  So it would be `prisoner-hub-drupal`.

**Comment by spikeheap** [comment]
Interesting @leonk, could you expand on the use-case for the prefix? 

In the local development context, Docker Compose prefixes containers with the directory name, so you end up with `prisoner-content-hub_drupal_1` where the directory is `prisoner-content-hub` and the service name is `drupal`.

Our main use-case for Docker Compose is local development, so the motivation for shorter names is mostly around developer experience, e.g. typing `docker-compose run --rm drupal` is significantly shorter than `docker-compose run --rm prisoner-content-hub-drupal`. 

The previous names were `hub-frontend` and `drupal`. This was intentional (because `frontend` felt meaningless), but I can see how it would come across as being inconsistent. Well out of scope of this PR, but it'd be great to come up wit ha better name for the "frontend".

I'm still happy either way. We could even merge this one to regain consistency, and then revert it later if we wanted to.

**Comment by leonk** [comment]
The use-case for the prefix was simply to indicate that the name is something project-specific (i.e. something that we ourselves had created).  I think if I saw `drupal` I might have thought this was referencing the dockerhub Drupal container (and not a container that we build and maintain ourselves).

But not a huge deal at all, so happy to leave it and close this PR.

**Review by andrewrlee — APPROVED** [review]
LGTM

**Pull request merged**
