### PR TITLE
Add gitcrypt to repository

### PR DESCRIPTION
**Pull request by davidthomas22**

### CODE REVIEW

**Review by psoleckimoj — APPROVED** [review]
LGTM!

**Comment by davidthomas22** [comment]
@psoleckimoj @LucasCairns You should be able to pull down this branch and run git-crypt unlock to view the encrypted file

**Comment by psoleckimoj** [comment]
> @psoleckimoj @LucasCairns You should be able to pull down this branch and run git-crypt unlock to view the encrypted file

Works a treat :)

**Review by LucasCairns — COMMENTED** [review]
Confirmed working for me

**Review by LucasCairns — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
